services:
  - type: web
    name: smart-server-ws
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PORT
        value: 8080 